[book]
title = "Robotics Handbook: A Guide to Perception, Navigation, and Control"
authors = ["Mitchell Scott"]
language = "en"
text-direction = "ltr"
src = "src"

[build]
build-dir = "target/book"
create-missing = true
use-default-preprocessors = true # use the default preprocessors

[rust]
edition = "2024"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
