[book]
title = "Robotics Handbook: A Guide to Perception, Navigation, and Control"
author = "Mitchell Scott"
language = "en"
multilingual = false
text-direction = "ltr"
src = "src"

[build]
build-dir = "target/book"
create-missing = true
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []

[rust]
edition = "2024"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"

[preprocessor.katex]
after = ["links"]
# KaTeX options.
output = "html"
leqno = false
fleqn = false
throw-on-error = true
error-color = "#cc0000"
min-rule-thickness = -1.0
max-size = "Infinity"
max-expand = 1000
trust = false
# Extra options.
no-css = false
include-src = false
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
pre-render = true

[preprocessor.bib]
bibliography = "bibliography.bib"

