# Sample workflow for building and deploying a mdBook site to GitHub Pages
#
# To get started with mdBook see: https://rust-lang.github.io/mdBook/index.html
#
# Edited by scott.mitchell913@gmail.com to build on all push/PR but only deploy
# from master after a PR merges with master.
# * 10/14/25 - Added linter job to make suggestions on PRs
name: build

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.48
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
          cargo install mdbook-katex mdbook-bib
      - name: Build with mdBook
        run: mdbook build
      
      - name: Upload artifact
        if: github.event.pull_request.merged == true
        uses: actions/upload-pages-artifact@v3
        with:
          name: mdbook-artifact
          path: ./target/book