name: CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with mdBook
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            mdbook build
      - name: Upload docs artifact
        if: github.ref == 'refs/heads/master'
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/book/
  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    concurrency:
      group: "pages"
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
